title: Leo Adams
url: http://eduos.github.io/
description: 'I am a graduate student from East China Normal University majoring in educational technology. I am pursuing a dream job of programming in the near future.'
keywords:
 - Leo Adams
 - Zhang Le
 - Leo

author:
    name: Leo Adams
    email: fanle_2013@163.com
    twitter: http://twitter.com/LeoAdams
    github: http://github.com/eduOS
    delicious: http://delicious.com/leoadamszhang
    quora: http://www.quora.com/Leo-Adams-2
    googleplus: http://plus.google.com/+LeoAdamszhang
    facebook: http://www.facebook.com/leo.adams.zhang
    linkedin: 
    avatar: 
    openid:
        server: 
        delegate: 
    
sections:
 - projects
 - about
 - journal 
 - answers
stylesheets:
 - /assets/themes/default/css/screen.css?52480=52480
 - /assets/themes/default/css/print.css
scripts:
 - http://ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js    
 - /assets/themes/default/js/site.min.js?131513?131513
colors:
    highlights:
        blue: '#009ff7'
        green: '#87d14b'
        red: '#FF007C'
    mono:
        dark: '#000000'
        medium: '#777777'
        light: '#FFFFFF'
    bg: '#EAF1F4'
    
pygments: true
permalink: pretty 
exclude:
 - Rakefile
 - README.markdown
 - .git
